version: '3.4'

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend
  qunity:
    image: ${DOCKER_REGISTRY-}qunity
    build:
      context: .
      dockerfile: Qunity/Dockerfile
    depends_on:
      - db
    networks:
      - backend
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy.conf:/etc/nginx/proxy.conf
      - ./mime.types:/etc/nginx/mime.types
      - ./Qunity/wwwroot:/static/
    ports:
      - "443:443"
    depends_on:
      - qunity
    networks:
      - backend
      - frontend

volumes:
  pgdata:

networks:
  backend:
  frontend: